- hosts: loadbalancer,masters
  gather_facts: yes
  become: true
  tasks:
    - name: update APT packages
      apt:
        update_cache: yes
      when: "'loadbalancer' in group_names"    

    - name: Install Haproxy packages
      apt:
        name: haproxy,policycoreutils,selinux-basics,selinux-utils
        state: present
      when: "'loadbalancer' in group_names"
    - name: activate selinux
      shell: |
        selinux-activate
      when: "'loadbalancer' in group_names"  
    - name: reboot and wait for reboot to complete
      reboot:
      when: "'loadbalancer' in group_names"
    - name: Haproxy conf template
      template:
        src: ./haproxy.conf.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: 0644
      when: "'loadbalancer' in group_names"
    - name: Haproxy ssl certificate
      template:
        src: ./apiserver.datasirpi.com.pem
        dest: /etc/ssl/certs/apiserver.datasirpi.com
        mode: 0600
      when: "'loadbalancer' in group_names"        
    - name: Semanage allows http 6443 port
      seport:
        ports: "{{ item }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: "'loadbalancer' in group_names"
      loop:
        - 6443
        - 9000        
    - name: Start Haproxy
      service:
        name: haproxy
        enabled: yes
        state: restarted
      when: "'loadbalancer' in group_names"
